2025-06-11 06:26:19,929 - INFO - 1. TEFAS fiyat indiriliyor basliyor...
2025-06-11 06:31:53,235 - INFO - 1. TEFAS fiyat indiriliyor tamamlandi.
2025-06-11 06:31:53,259 - INFO - 2. HTML dosyalari uretiliyor basliyor...
2025-06-11 06:31:55,100 - INFO - 2. HTML dosyalari uretiliyor tamamlandi.
2025-06-11 06:31:55,100 - INFO - 3. GitHub'a yukleniyor basliyor...
2025-06-11 06:31:58,547 - INFO - 3. GitHub'a yukleniyor tamamlandi.
2025-06-11 06:33:55,872 - INFO - 1. TEFAS fiyat indiriliyor basliyor...
2025-06-11 06:49:28,332 - ERROR - 1. TEFAS fiyat indiriliyor sirasinda hata: C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat(new_data_frames, ignore_index=True)
C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat(new_data_frames, ignore_index=True)
C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat(new_data_frames, ignore_index=True)
C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat(new_data_frames, ignore_index=True)
C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat(new_data_frames, ignore_index=True)
C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat(new_data_frames, ignore_index=True)
C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_data = pd.concat(new_data_frames, ignore_index=True)
Traceback (most recent call last):
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\urllib3\connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 1375, in getresponse
    response.begin()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yahya\Documents\fund_price_upload\tefas_fiyat_indir_pp_uyumlu_final_guncel.py", line 66, in <module>
    df = tefas.fetch(start=str(month_start), end=str(interval_end), name=fon_adi, columns=["date", "price"])
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tefas\crawler.py", line 105, in fetch
    info = self._do_post(self.info_endpoint, data)
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tefas\crawler.py", line 126, in _do_post
    response = self.session.post(
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\yahya\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

2025-06-11 19:00:04,091 - INFO - 1. TEFAS fiyat indiriliyor basliyor...
2025-06-11 19:00:09,875 - INFO - 1. TEFAS fiyat indiriliyor tamamlandi.
2025-06-11 19:00:09,875 - INFO - 2. HTML dosyalari uretiliyor basliyor...
2025-06-11 19:00:11,056 - INFO - 2. HTML dosyalari uretiliyor tamamlandi.
2025-06-11 19:00:11,056 - INFO - 3. GitHub'a yukleniyor basliyor...
2025-06-11 19:00:14,413 - INFO - 3. GitHub'a yukleniyor tamamlandi.
2025-06-11 20:38:00,236 - INFO - 1. TEFAS fiyat indiriliyor basliyor...
2025-06-11 20:42:11,505 - INFO - 1. TEFAS fiyat indiriliyor tamamlandi.
2025-06-11 20:42:11,517 - INFO - 2. HTML dosyalari uretiliyor basliyor...
2025-06-11 20:42:13,665 - INFO - 2. HTML dosyalari uretiliyor tamamlandi.
2025-06-11 20:42:13,667 - INFO - 3. GitHub'a yukleniyor basliyor...
2025-06-11 20:42:17,474 - INFO - 3. GitHub'a yukleniyor tamamlandi.
